name: Node CI

on: 
  pull_request:
    branches:
      - master
  push: 

jobs:
  AVA:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npx ava

  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run lint

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@v1
